/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Cliente;
import Dao.ClienteDao;
import Table.ClienteTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author leticia_2
 */
public class TelaCadastroCliente extends javax.swing.JInternalFrame{

    /**
     * Creates new form TelaCadastroCliente
     */
    Cliente cli = new Cliente();
    ClienteDao clt = new ClienteDao();
    public TelaCadastroCliente() {
        initComponents();
        
        listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxNomeCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxEndCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxDnCli = new javax.swing.JFormattedTextField();
        TxEmailCli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxBairro = new javax.swing.JTextField();
        TxCidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxCpfCli = new javax.swing.JFormattedTextField();
        TxCnhCli = new javax.swing.JFormattedTextField();
        TxRgCli = new javax.swing.JFormattedTextField();
        TxTelCli = new javax.swing.JFormattedTextField();
        TxCep = new javax.swing.JFormattedTextField();
        TxSexo = new javax.swing.JTextField();
        btcad = new javax.swing.JButton();
        BtnExcluirCli = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxCod = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Cliente");
        setPreferredSize(new java.awt.Dimension(874, 513));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais "));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(874, 513));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome Completo ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 160, 30);
        jPanel1.add(TxNomeCli);
        TxNomeCli.setBounds(7, 50, 470, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Endereço");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 137, 100, 30);
        jPanel1.add(TxEndCli);
        TxEndCli.setBounds(10, 170, 359, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cep");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 150, 27, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CPF");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(6, 86, 70, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CNH");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(144, 86, 32, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefone ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 87, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Data de Nascimento ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 20, 142, 30);

        try {
            TxDnCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxDnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDnCliActionPerformed(evt);
            }
        });
        jPanel1.add(TxDnCli);
        TxDnCli.setBounds(520, 50, 142, 30);
        jPanel1.add(TxEmailCli);
        TxEmailCli.setBounds(10, 240, 334, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("E-mail ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 210, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("RG");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(298, 86, 20, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Sexo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(600, 80, 60, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Bairro");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(660, 147, 42, 20);
        jPanel1.add(TxBairro);
        TxBairro.setBounds(660, 170, 102, 30);
        jPanel1.add(TxCidade);
        TxCidade.setBounds(800, 170, 91, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Cidade");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(800, 137, 47, 30);

        try {
            TxCpfCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TxCpfCli);
        TxCpfCli.setBounds(6, 109, 109, 30);

        try {
            TxCnhCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TxCnhCli);
        TxCnhCli.setBounds(130, 110, 109, 30);

        try {
            TxRgCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TxRgCli);
        TxRgCli.setBounds(260, 109, 107, 30);

        try {
            TxTelCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TxTelCli);
        TxTelCli.setBounds(420, 110, 109, 30);

        try {
            TxCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(TxCep);
        TxCep.setBounds(390, 170, 252, 30);

        TxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxSexoActionPerformed(evt);
            }
        });
        jPanel1.add(TxSexo);
        TxSexo.setBounds(600, 110, 83, 30);

        btcad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btcad.setText("Salvar");
        btcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadActionPerformed(evt);
            }
        });
        jPanel1.add(btcad);
        btcad.setBounds(550, 240, 75, 25);

        BtnExcluirCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExcluirCli.setText("Excluir");
        BtnExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirCliActionPerformed(evt);
            }
        });
        jPanel1.add(BtnExcluirCli);
        BtnExcluirCli.setBounds(650, 240, 90, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EssentialMotors1.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(890, 20, 180, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Código");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(750, 20, 90, 20);

        TxCod.setEditable(false);
        TxCod.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(TxCod);
        TxCod.setBounds(740, 50, 100, 30);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "Nascimento", "Sexo", "E-mail", "Telefone", "Endereço", "Bairro", "Cidade", "CEP", "CNH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setPreferredSize(new java.awt.Dimension(874, 513));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 280, 1260, 290);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(120, 110, 10, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 110, 10, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(120, 110, 10, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(120, 110, 10, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(240, 110, 10, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(670, 50, 10, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(480, 50, 10, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadActionPerformed
        //Cadastro de dados 
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy"); // Formato de data usual
                      
        cli.setNome(TxNomeCli.getText());                
        cli.setCpf(TxCpfCli.getText());
        cli.setRg(TxRgCli.getText());
        
          TxCpfCli.setText(" ");
        TxRgCli.setText(" ");
        
        try {
            // Converte para o tipo de Date (util) e retorna um long para o Date (SQL)
            cli.setDataNascimento(new java.sql.Date(df.parse(TxDnCli.getText()).getTime()));
        } catch (ParseException ex) {
            ex.printStackTrace(); // Mostra o erro detalhado

            System.out.println("Erro: " + ex.getMessage()); // Mostra o erro
        }
        TxDnCli.setText("  /  /     ");
        
        cli.setSexo(TxSexo.getText());
        cli.setEmail(TxEmailCli.getText());
        cli.setTelefone(TxTelCli.getText());
        cli.setEndereco(TxEndCli.getText());
        cli.setBairro(TxBairro.getText());
        cli.setCidade(TxCidade.getText());
        cli.setCep(TxCep.getText());
        cli.setCnh(TxCnhCli.getText());
                                        
        if(TxCod.getText().equals("")) {
            if(clt.cadastrar(cli))
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso");
        } else {
            cli.setClienteId(Integer.parseInt(TxCod.getText()));
            
            if(clt.alterar(cli))
                JOptionPane.showMessageDialog(null, "Cliente editado com sucesso");
        }
        
        listarClientes();
        TxNomeCli.setText("");
        TxCpfCli.setText("");
        TxRgCli.setText("");
        TxDnCli.setText("");
        TxSexo.setText("");
        TxEmailCli.setText("");
        TxEndCli.setText("");
        TxBairro.setText("");
        TxCidade.setText("");
        TxCep.setText("");
        TxTelCli.setText("");
        TxCnhCli.setText("");
        
        TxNomeCli.requestFocus();
        

    }//GEN-LAST:event_btcadActionPerformed
  
    private void BtnExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirCliActionPerformed
           
            int respostas = 0;
            
        if(TxCod.getText().isEmpty() == false) {
            //if(clt.excluir(Integer.parseInt(TxCod.getText())))
            respostas = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente exlcuir?");
            if (respostas == JOptionPane.YES_OPTION){
               if(clt.excluir(Integer.parseInt(TxCod.getText())));
                
            }
                           
            }
              

            
            listarClientes();
        TxNomeCli.setText("");
        TxCpfCli.setText("");
        TxRgCli.setText("");
        TxDnCli.setText("");
        TxSexo.setText("");
        TxEmailCli.setText("");
        TxEndCli.setText("");
        TxBairro.setText("");
        TxCidade.setText("");
        TxCep.setText("");
        TxTelCli.setText("");
        TxCnhCli.setText("");
        
        TxNomeCli.requestFocus();
        
    }//GEN-LAST:event_BtnExcluirCliActionPerformed

    private void TxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxSexoActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        if(jTableClientes.getSelectedRowCount() > 0) {
            if(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0) != null)
                preencherCampos();
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void TxDnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDnCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDnCliActionPerformed

    private void preencherCampos() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        
        TxCod.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString());
        TxNomeCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1).toString());
        TxCpfCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 2).toString());
        TxRgCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 3).toString());
        TxDnCli.setText(df.format(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 4)));
        TxSexo.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 5).toString());
        TxEmailCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 6).toString());
        TxTelCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 7).toString());
        TxEndCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 8).toString());
        TxBairro.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 9).toString());
        TxCidade.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 10).toString());
        TxCep.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 11).toString());
        TxCnhCli.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 12).toString());
    }
    
    private void listarClientes() {
        DefaultTableModel tab = (DefaultTableModel) jTableClientes.getModel();
        
        tab.setNumRows(0);
        
        ArrayList<Cliente> clientes = clt.listarTodos();                
        
        for(Cliente cliente : clientes) {
            tab.addRow(new Object[] {cliente.getClienteId(), cliente.getNome(), cliente.getCpf(), cliente.getRg(), cliente.getDataNascimento(), 
                cliente.getSexo(), cliente.getEmail(), cliente.getTelefone(), cliente.getEndereco(), cliente.getBairro(), cliente.getCidade(), 
                cliente.getCep(), cliente.getCnh()});
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluirCli;
    private javax.swing.JTextField TxBairro;
    private javax.swing.JFormattedTextField TxCep;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JFormattedTextField TxCnhCli;
    private javax.swing.JTextField TxCod;
    private javax.swing.JFormattedTextField TxCpfCli;
    private javax.swing.JFormattedTextField TxDnCli;
    private javax.swing.JTextField TxEmailCli;
    private javax.swing.JTextField TxEndCli;
    private javax.swing.JTextField TxNomeCli;
    private javax.swing.JFormattedTextField TxRgCli;
    private javax.swing.JTextField TxSexo;
    private javax.swing.JFormattedTextField TxTelCli;
    private javax.swing.JButton btcad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
}
