/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Fornecedor;
import Dao.FornecedorDao;
import Table.FornecedorTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;





/**
 *
 * @author aluno
 */
public class TelaFornecedor extends javax.swing.JInternalFrame {

   Fornecedor forn = new Fornecedor();
   FornecedorDao forne = new FornecedorDao();
    public TelaFornecedor() {
     initComponents();
   
        
        listarFornecedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxNomeFantasia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxNomeFant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxRazao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxEnd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxCnpj = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        TxTel = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        TxBairro = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        TxCep = new javax.swing.JFormattedTextField();
        jLabel44 = new javax.swing.JLabel();
        bntcadastrar = new javax.swing.JButton();
        bntexcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbforn = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Fornecedores");
        setAutoscrolls(true);

        TxNomeFantasia.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Empresa "));
        TxNomeFantasia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome Fantasia ");
        TxNomeFantasia.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));
        TxNomeFantasia.add(TxNomeFant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Razão Social");
        TxNomeFantasia.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 81, -1, -1));
        TxNomeFantasia.add(TxRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 410, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Endereço");
        TxNomeFantasia.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 133, -1, -1));
        TxNomeFantasia.add(TxEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 410, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("CNPJ");
        TxNomeFantasia.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        try {
            TxCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxNomeFantasia.add(TxCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Telefone ");
        TxNomeFantasia.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        try {
            TxTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxNomeFantasia.add(TxTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Bairro ");
        TxNomeFantasia.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));
        TxNomeFantasia.add(TxBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("CEP");
        TxNomeFantasia.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        try {
            TxCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxNomeFantasia.add(TxCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 130, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EssentialMotors1.png"))); // NOI18N
        TxNomeFantasia.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        bntcadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntcadastrar.setText("Salvar");
        bntcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntcadastrarActionPerformed(evt);
            }
        });
        TxNomeFantasia.add(bntcadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        bntexcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntexcluir.setText("Excluir");
        bntexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntexcluirActionPerformed(evt);
            }
        });
        TxNomeFantasia.add(bntexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Código");
        TxNomeFantasia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        TxCod.setEditable(false);
        TxCod.setBackground(new java.awt.Color(102, 102, 102));
        TxNomeFantasia.add(TxCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        TxNomeFantasia.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        TxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxEmailActionPerformed(evt);
            }
        });
        TxNomeFantasia.add(TxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 400, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cidade");
        TxNomeFantasia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));
        TxNomeFantasia.add(TxCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");
        TxNomeFantasia.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");
        TxNomeFantasia.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");
        TxNomeFantasia.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");
        TxNomeFantasia.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");
        TxNomeFantasia.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");
        TxNomeFantasia.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("*");
        TxNomeFantasia.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 20));

        tbforn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbforn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfornMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbforn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TxNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbfornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfornMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbfornMouseClicked

    private void bntcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntcadastrarActionPerformed
    
        
               
    }//GEN-LAST:event_bntcadastrarActionPerformed

    private void TxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxEmailActionPerformed

    private void bntexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntexcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxBairro;
    private javax.swing.JFormattedTextField TxCep;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JFormattedTextField TxCnpj;
    private javax.swing.JTextField TxCod;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JTextField TxEnd;
    private javax.swing.JTextField TxNomeFant;
    private javax.swing.JPanel TxNomeFantasia;
    private javax.swing.JTextField TxRazao;
    private javax.swing.JFormattedTextField TxTel;
    private javax.swing.JButton bntcadastrar;
    private javax.swing.JButton bntexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbforn;
    // End of variables declaration//GEN-END:variables

    private void listarFornecedores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
