/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Locacao;
import Dao.LocacaoDao;
import Table.ClienteTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 *
 * @author leticia_2
 */
public class TelaLocacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLocacao
     */
    Locacao loc = new Locacao();
    LocacaoDao lcc = new LocacaoDao();
    public TelaLocacao() {
        initComponents();
         listarLocacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxNomeCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxDLoc = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxDEn = new javax.swing.JFormattedTextField();
        TxServicos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxMarca = new javax.swing.JTextField();
        TxPlaca = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxDevol = new javax.swing.JFormattedTextField();
        BtnReserva = new javax.swing.JButton();
        BtnExcluirLoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbLocacao = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxCod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Locação ");
        setPreferredSize(new java.awt.Dimension(874, 513));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais "));
        jPanel1.setPreferredSize(new java.awt.Dimension(874, 513));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nome Completo ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Serviços");

        try {
            TxDLoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Data da Entrega");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Data da Locação ");

        try {
            TxDEn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Marca");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Placa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Devolução ");

        try {
            TxDevol.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BtnReserva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnReserva.setText("Reservar");
        BtnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReservaActionPerformed(evt);
            }
        });

        BtnExcluirLoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExcluirLoc.setText("Excluir");
        BtnExcluirLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirLocActionPerformed(evt);
            }
        });

        TbLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idlocacao", "nome ", "chn", "dataLocacao", "dataEntrega", "servicos", "funcionarioID", "clienteID", "veiculoID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbLocacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbLocacao);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EssentialMotors1.png"))); // NOI18N
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Código");

        TxCod.setEditable(false);
        TxCod.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel14))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(TxDevol, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel11)
                                        .addGap(105, 105, 105)
                                        .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxDLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxDEn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(611, 611, 611)
                        .addComponent(BtnReserva)
                        .addGap(47, 47, 47)
                        .addComponent(BtnExcluirLoc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxDLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxDEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxMarca)
                                    .addComponent(TxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxDevol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReserva)
                    .addComponent(BtnExcluirLoc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReservaActionPerformed
    //Cadastro de dados 
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy"); // Formato de data usual
                      
        loc.setNomeCliente(TxNomeCli.getText());                
  
        
         
        
        try {
            // Converte para o tipo de Date (util) e retorna um long para o Date (SQL)
            loc.setDataLocacao(new java.sql.Date(df.parse(TxDLoc.getText()).getTime()));
            loc.setDataEntrega(new java.sql.Date(df.parse(TxDEn.getText()).getTime()));
            loc.setDataDevolucao(new java.sql.Date(df.parse(TxDevol.getText()).getTime()));
        } catch (ParseException ex) {
            ex.printStackTrace(); // Mostra o erro detalhado

            System.out.println("Erro: " + ex.getMessage()); // Mostra o erro
        }
        TxDLoc.setText("  /  /     ");
         TxDEn.setText("  /  /     ");
          TxDevol.setText("  /  /     ");
          
        loc.setServicos(TxServicos.getText());
        loc.setMarca(TxMarca.getText());
        loc.setPlaca(TxPlaca.getText());
      
                                        
        if(TxCod.getText().equals("")) {
            if(lcc.cadastrar(loc))
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso");
        } else {
            loc.setIdLocacao(Integer.parseInt(TxCod.getText()));
            
            if(lcc.alterar(loc))
                JOptionPane.showMessageDialog(null, "Cliente editado com sucesso");
        }
        
        listarLocacao();
        TxNomeCli.setText("");
        TxDLoc.setText("");
        TxDEn.setText("");
        TxDevol.setText("");
        TxServicos.setText("");
        TxMarca.setText("");
        TxPlaca.setText("");
        
        
        TxNomeCli.requestFocus();
        
        
        
    }//GEN-LAST:event_BtnReservaActionPerformed

    private void TbLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbLocacaoMouseClicked
     if(TbLocacao.getSelectedRowCount() > 0) {
            if(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 0) != null)
                preencherCampos();
        }
         
        
    }//GEN-LAST:event_TbLocacaoMouseClicked
        
    private void BtnExcluirLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirLocActionPerformed
      if(TxCod.getText().isEmpty() == false) {
            if(lcc.excluir(Integer.parseInt(TxCod.getText())))
                JOptionPane.showMessageDialog(null, "Cliente apagado com sucesso");
            
            listarLocacao();
       TxNomeCli.setText("");
        TxDLoc.setText("");
        TxDEn.setText("");
        TxDevol.setText("");
        TxServicos.setText("");
        TxMarca.setText("");
        TxPlaca.setText("");
        
        
        TxNomeCli.requestFocus();
        
      
        }
    }//GEN-LAST:event_BtnExcluirLocActionPerformed
           

    private void listarLocacao() {
        DefaultTableModel tab = (DefaultTableModel) TbLocacao.getModel();
        
        tab.setNumRows(0);
        
        ArrayList<Locacao> loc = lcc.listarTodos();                
        
        for(Locacao locacao : loc) {
            tab.addRow(new Object[] {locacao.getIdLocacao(), locacao.getNomeCliente(),  locacao.getDataLocacao(), locacao.getDataEntrega(), 
                locacao.getDataDevolucao(), locacao.getServicos(), locacao.getPlaca(), locacao.getMarca()}  );
        
    }
    }
     private void preencherCampos() {
           DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        
        TxCod.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 0).toString());
        TxNomeCli.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 1).toString());
        TxDLoc.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 2).toString());
        TxDEn.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 3).toString());
        TxDevol.setText(df.format(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 4)));
        TxServicos.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 5).toString());
        TxMarca.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 6).toString());
        TxPlaca.setText(TbLocacao.getValueAt(TbLocacao.getSelectedRow(), 7).toString());
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExcluirLoc;
    private javax.swing.JButton BtnReserva;
    private javax.swing.JTable TbLocacao;
    private javax.swing.JTextField TxCod;
    private javax.swing.JFormattedTextField TxDEn;
    private javax.swing.JFormattedTextField TxDLoc;
    private javax.swing.JFormattedTextField TxDevol;
    private javax.swing.JTextField TxMarca;
    private javax.swing.JTextField TxNomeCli;
    private javax.swing.JFormattedTextField TxPlaca;
    private javax.swing.JTextField TxServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   

   


    
}
