/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author leticia_2
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
      //  setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        desktop1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        TelaCliente = new javax.swing.JMenu();
        CadCliente = new javax.swing.JMenuItem();
        TelaFunc = new javax.swing.JMenu();
        CadFunc = new javax.swing.JMenuItem();
        TelaLoc = new javax.swing.JMenu();
        CadLoc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CadFrota = new javax.swing.JMenuItem();
        TelaForn = new javax.swing.JMenu();
        CadForn = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Essential ");
        setExtendedState(6);

        desktop1.setPreferredSize(new java.awt.Dimension(1362, 1362));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo nova.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(874, 874));
        jLabel2.setPreferredSize(new java.awt.Dimension(1362, 1362));

        desktop1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(854, Short.MAX_VALUE))
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addGap(468, 468, 468))
        );

        TelaCliente.setText("Cliente");

        CadCliente.setText("Cadastro");
        CadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteActionPerformed(evt);
            }
        });
        TelaCliente.add(CadCliente);

        jMenuBar2.add(TelaCliente);

        TelaFunc.setText("Funcionario");

        CadFunc.setText("Cadastro");
        CadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFuncActionPerformed(evt);
            }
        });
        TelaFunc.add(CadFunc);

        jMenuBar2.add(TelaFunc);

        TelaLoc.setText("Locacão ");

        CadLoc.setText("Cadastro");
        CadLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadLocActionPerformed(evt);
            }
        });
        TelaLoc.add(CadLoc);

        jMenuBar2.add(TelaLoc);

        jMenu2.setText("Frota");

        CadFrota.setText("Cadastro");
        CadFrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFrotaActionPerformed(evt);
            }
        });
        jMenu2.add(CadFrota);

        jMenuBar2.add(jMenu2);

        TelaForn.setText("Fornecedor");

        CadForn.setText("Cadastro");
        CadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFornActionPerformed(evt);
            }
        });
        TelaForn.add(CadForn);

        jMenuBar2.add(TelaForn);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.PREFERRED_SIZE, 2177, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop1, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2263, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFuncActionPerformed
        // TODO add your handling code here:
         TelaFuncionario TelaFunc = new TelaFuncionario();
         desktop1.add(TelaFunc);
            TelaFunc.setVisible(true);
    }//GEN-LAST:event_CadFuncActionPerformed

    private void CadFrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFrotaActionPerformed
        // TODO add your handling code here:
          TelaCadastroFrota TelaFrota = new TelaCadastroFrota();
          desktop1.add(TelaFrota);
                TelaFrota.setVisible(true);
    }//GEN-LAST:event_CadFrotaActionPerformed

    private void CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteActionPerformed
        // TODO add your handling code here:
          TelaCadastroCliente TelaCliente = new TelaCadastroCliente();
          desktop1.add(TelaCliente);
                TelaCliente.setVisible(true);
    }//GEN-LAST:event_CadClienteActionPerformed

    private void CadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFornActionPerformed
        // TODO add your handling code here:
          TelaFornecedor TelaForn = new TelaFornecedor();
          desktop1.add(TelaForn);
                TelaForn.setVisible(true);
    }//GEN-LAST:event_CadFornActionPerformed

    private void CadLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadLocActionPerformed
        // TODO add your handling code here:
       TelaLocacao TelaLoc = new TelaLocacao();
        desktop1.add(TelaLoc);
            TelaLoc.setVisible(true);
        
    }//GEN-LAST:event_CadLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadCliente;
    private javax.swing.JMenuItem CadForn;
    private javax.swing.JMenuItem CadFrota;
    private javax.swing.JMenuItem CadFunc;
    private javax.swing.JMenuItem CadLoc;
    private javax.swing.JMenu TelaCliente;
    private javax.swing.JMenu TelaForn;
    private javax.swing.JMenu TelaFunc;
    private javax.swing.JMenu TelaLoc;
    private javax.swing.JDesktopPane desktop1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
