/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Funcionario;
import Dao.FuncionarioDao;
import Table.ClienteTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author leticia_2
 */
public class TelaCadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroFuncionarioEssencial
     */
    Funcionario func = new Funcionario();
    FuncionarioDao funci = new FuncionarioDao();
    public TelaCadastroFuncionario() {
        initComponents();
        
        listarfuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory(null).createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TxNomeFunc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxCpfFunc = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        TxRgFunc = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        TxTelFunc = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        TxCepFunc = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        TxDn = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxEndFunc = new javax.swing.JTextField();
        TxBairroFunc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxEmailFunc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxFuncao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxSenha = new javax.swing.JPasswordField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbfunc = new javax.swing.JTable();
        btncadastrofunc = new javax.swing.JButton();
        btnexcluircliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxCod = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(874, 513));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanel2.setPreferredSize(new java.awt.Dimension(874, 513));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nome Completo ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CPF");

        try {
            TxCpfFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("RG");

        try {
            TxRgFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Telefone ");

        try {
            TxTelFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CEP");

        try {
            TxCepFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Data de Nascimento ");

        try {
            TxDn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Endereço");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Bairro");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("E-mail ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuário ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Senha ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Função ");

        tbfunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FuncionárioID", "Nome", "CPF", "RG", "Data de Nascimento", "Email", "Telefone", "Endereço", "CEP", "Login", "Senha", "Função"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbfunc.setPreferredSize(new java.awt.Dimension(874, 513));
        tbfunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfuncMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbfunc);

        btncadastrofunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncadastrofunc.setText("Cadastro");
        btncadastrofunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrofuncActionPerformed(evt);
            }
        });

        btnexcluircliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexcluircliente.setText("Excluir");
        btnexcluircliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirclienteActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EssentialMotors1.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Código");

        TxCod.setEditable(false);
        TxCod.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(TxNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(TxCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxRgFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(TxTelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(52, 52, 52)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(TxDn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(87, 87, 87)
                                                        .addComponent(jLabel12))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(56, 56, 56)
                                                        .addComponent(TxCod, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(TxBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(TxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxEndFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(TxEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncadastrofunc)
                .addGap(18, 18, 18)
                .addComponent(btnexcluircliente)
                .addGap(417, 417, 417))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TxNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TxCod)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(TxDn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxRgFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxTelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxEndFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncadastrofunc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnexcluircliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncadastrofuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrofuncActionPerformed
        //Cadastro de dados 
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy"); // Formato de data usual
                      
        func.setNome(TxNomeFunc.getText());                
        func.setCpf(TxCpfFunc.getText());
        func.setRg(TxRgFunc.getText());
        
         try {
            // Converte para o tipo de Date (util) e retorna um long para o Date (SQL)
            func.setDataNascimento(new java.sql.Date(df.parse(TxDn.getText()).getTime()));
        } catch (ParseException ex) {
            ex.printStackTrace(); // Mostra o erro detalhado

            System.out.println("Erro: " + ex.getMessage()); // Mostra o erro
        }
        TxDn.setText("  /  /     ");
        
        
        func.setEmail(TxEmailFunc.getText());
        func.setTelefone(TxTelFunc.getText());
        func.setEndereco(TxEndFunc.getText());
        func.setBairro(TxBairroFunc.getText());
        //func.setCidade(TxCidade.getText());
        func.setCep(TxCepFunc.getText());
        func.setUsuario(TxUsuario.getText());
         func.setSenha(TxSenha.getText());
         func.setFuncao(TxFuncao.getText());
                                        
        if(TxCod.getText().equals("")) {
            if(funci.cadastrar(func))
                JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso");
        } else {
            func.setFuncionarioID(Integer.parseInt(TxCod.getText()));
            
            if(funci.alterar(func))
                JOptionPane.showMessageDialog(null, "Funcionario editado com sucesso");
        }
        
        listarfuncionarios();
        TxNomeFunc.setText(" ");
        TxCpfFunc.setText(" ");
        TxRgFunc.setText(" ");
        TxDn.setText(" ");      
        TxEmailFunc.setText(" ");
        TxEndFunc.setText(" ");
        TxBairroFunc.setText(" ");
        TxCepFunc.setText(" ");
        TxUsuario.setText(" ");
        TxSenha.setText(" ");
        TxFuncao.requestFocus();
        
        
    }//GEN-LAST:event_btncadastrofuncActionPerformed

    private void tbfuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfuncMouseClicked
        if(tbfunc.getSelectedRowCount() > 0) {
            if(tbfunc.getValueAt(tbfunc.getSelectedRow(), 0) != null)
                preencherCampos();
        }
    }
        
    
    private void listarfuncionarios() {
        DefaultTableModel tab = (DefaultTableModel) tbfunc.getModel();
        
        tab.setNumRows(0);
        
        ArrayList<Funcionario> funcionarios = funci.listarTodos();                
        
        for(Funcionario funcionario : funcionarios) {
            tab.addRow(new Object[] {funcionario.getFuncionarioID(), funcionario.getNome(), funcionario.getCpf(), funcionario.getRg(), funcionario.getDataNascimento(), 
                 funcionario.getEmail(), funcionario.getTelefone(), funcionario.getEndereco(), funcionario.getCep(), funcionario.getUsuario(), 
                funcionario.getSenha(), funcionario.getFuncao()});
        }
    }//GEN-LAST:event_tbfuncMouseClicked

    private void btnexcluirclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirclienteActionPerformed
                                        
        if(TxCod.getText().isEmpty() == false) {
            if(funci.Excluir(Integer.parseInt(TxCod.getText())))
                JOptionPane.showMessageDialog(null, "Funcionario apagado com sucesso");
    }//GEN-LAST:event_btnexcluirclienteActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxBairroFunc;
    private javax.swing.JFormattedTextField TxCepFunc;
    private javax.swing.JTextField TxCod;
    private javax.swing.JFormattedTextField TxCpfFunc;
    private javax.swing.JFormattedTextField TxDn;
    private javax.swing.JTextField TxEmailFunc;
    private javax.swing.JTextField TxEndFunc;
    private javax.swing.JTextField TxFuncao;
    private javax.swing.JTextField TxNomeFunc;
    private javax.swing.JFormattedTextField TxRgFunc;
    private javax.swing.JPasswordField TxSenha;
    private javax.swing.JFormattedTextField TxTelFunc;
    private javax.swing.JTextField TxUsuario;
    private javax.swing.JButton btncadastrofunc;
    private javax.swing.JButton btnexcluircliente;
    private java.util.List<view.Cliente> clienteList;
    private javax.persistence.Query clienteQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbfunc;
    // End of variables declaration//GEN-END:variables

    private void preencherCampos() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        
        TxCod.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 0).toString());
        TxNomeFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 1).toString());
        TxCpfFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 2).toString());
        TxRgFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 3).toString());
        TxDn.setText(df.format(tbfunc.getValueAt(tbfunc.getSelectedRow(), 4)));
        TxEmailFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 5).toString());
        TxEndFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 6).toString());
        TxBairroFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 7).toString());
        TxCepFunc.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 8).toString());
        TxUsuario.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 9).toString());
        TxSenha.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 10).toString());
        TxFuncao.setText(tbfunc.getValueAt(tbfunc.getSelectedRow(), 11).toString());
    }

   

 
}
